### ISSUE TITLE
Server Sync

### ISSUE THREAD

**Issue by snarkyone** [Zaarthras/SimplyStamina#1]
Any chance we could get this so that my players can't just disable stamina outright?

Otherwise, great mod!   No stam usage drain when no enemies is perfect for my use :)

**Comment by Zaarthras** [comment]
Hi snarkyone,

I've updated the mod to include ServerSync to synchronize the configuration settings from the server to the client.
This is implemented in Version 1.1.0 which is now updated on Thunderstore (It may take a while until it is registered).

Best regards

**Comment by snarkyone** [comment]
You rock, thanks so much!
