### ISSUE TITLE
Performance Impact StackFrame()

### ISSUE THREAD

**Issue by ZenDragonX** [Zaarthras/SimplyStamina#2]
Hi, great mod!  However after installing it I noticed a dip in FPS even when doing nothing.  I am not 100% sure it's your mod, so in all fairness I could be wrong.  But I took a look at your code and I see that you are using new StackFrame() in the check for stamina usage.  Stamina usage check is a tight loop so it's calling that very frequently.  According to this article StackFrame is an expensive operation:

https://stackoverflow.com/questions/1348643/how-performant-is-stackframe

So perhaps an alternative method can be used or cache the results? (Careful about memory leaks if you opt for caching!)

Just a thought, perhaps something to look into. :)

And again... I may be wrong, just my hunch.

Thanks for the great mod!  Been looking for something like this!

**Comment by Zaarthras** [comment]
Hi ZenDragonX,

I have not noticed any frame drops yet, although I have a high-end PC so it would probably be harder to notice.

Another option I could think of would be patching the methods I'm checking for (Player.CheckRun, Player.OnJump, etc.) and setting a temporary value while they're executed.
I'll try that, benchmark the results, and come back to this issue once I know more.

Best regards

**Comment by Zaarthras** [comment]
I've implemented the changes and benchmarked the execution time of the `SimplyStaminaUseStaminaPatch.Prefix()` method:

The results on my PC are:
- Currently it takes 0.03 milliseconds on average
- With the changes made it takes 0.0005 milliseconds on average

I'll patch that in properly, run some tests, and then release it as an update later.

Thanks for the notice!

**Comment by Zaarthras** [comment]
I've just released version 1.1.1 where the optimizations are implemented.
However, I don't believe your initial dip in FPS has it's cause in this mod, as you wrote that they're dropping even when you're doing nothing. The code is only run whenever there's stamina usage, so if your FPS go down when standing still, it's probably something else causing it.

Best regards
